"""jira_tasks: add task_type, remove unique constraint

Revision ID: c059e7532535
Revises: c3bd96d21b76
Create Date: 2025-11-21 08:15:28.995321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c059e7532535'
down_revision = 'c3bd96d21b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jira_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jira_tasks', schema=None) as batch_op:
        batch_op.drop_column('task_type')

    # ### end Alembic commands ###
